<a href="https://colab.research.google.com/github/anubhavgupta1/Foundations-of-Python/blob/master/10_Mathematical_and_statistical_Functions_on_Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
from numpy import linalg as la

In [3]:
a = np.random.rand(3,4)
a

array([[0.74127206, 0.79214939, 0.22213276, 0.21053575],
       [0.38918201, 0.18844792, 0.98223511, 0.74780888],
       [0.87491287, 0.47018085, 0.35120759, 0.69322103]])

In [4]:
a.mean()

0.5552738508286571

In [5]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
#sum across matrices
c.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [7]:
#sum across columns
c.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [8]:
#sum across rows
c.sum(axis=-1)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [15]:
#transpose of matrix
cc = np.arange(6).reshape(2,3)
print(cc)
cc.T

[[0 1 2]
 [3 4 5]]


array([[0, 3],
       [1, 4],
       [2, 5]])

In [17]:
# solving a system of linear scalar equations
#2x + 6y = 6
#5x + 3y = -9
coeffs = np.array([[2,6],[5,3]])
depvars = np.array([6,-9])
sol = la.solve(coeffs,depvars)
sol

array([-3.,  2.])

In [18]:
coeffs.dot(sol)

array([ 6., -9.])