<a href="https://colab.research.google.com/github/anubhavgupta1/Foundations-of-Python/blob/master/9_Complete_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn.datasets import load_sample_image

In [2]:
#Creating Numpy array by passing a Python list
sample_list = [1,2,3]
list_array = np.array(sample_list)

In [3]:
#Creating Numpy array by passing a Python tuple
tup = (1,2,3)
my_tup_array = np.array(tup)

In [4]:
#Time comparison of a NumPy operation and a corresponding Python code
def multiply_loops(A, B):
  c=np.zeros((A.shape[0], B.shape[1]))
  for i in range(A.shape[0]):
    for k in range(B.shape[1]):
      c[i,k] = 0
      for j in range(B.shape[0]):
        n = A[i,j] * B[j,k]
        c[i,k] += n
  return c
def multiply_vector(A, B):
     return A @ B
X = np.random.random((100, 100))
Y = np.random.random((100, 100))
%timeit multiply_loops(X, Y)
%timeit multiply_vector(X, Y)

1 loop, best of 3: 778 ms per loop
The slowest run took 80.72 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 101 µs per loop


#NumPy - Arrays - Special Types of Arrays - Array filled with specific value
1. NumPy array with all its elements values as zero (using zeros() function of NumPy)
2. NumPy array with all its elements values as one (using ones() function of NumPy)
3. NumPy array with all its elements values as a specific given value (using full() function of NumPy)
4. Identity matrix or array

In [5]:
#Creating NumPy array with all its elements values as zero (using zeros() function of NumPy)
tup_dim = (3,4)
my_zeros_array = np.zeros(tup_dim, dtype=np.int16)
my_zeros_array


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [6]:
#Creating NumPy array with all its elements values as one (using ones() function of NumPy)
my_ones_array = np.ones(tup_dim, dtype=np.int16)
my_ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [7]:
#Creating NumPy array with all its elements values as a specific given value (using full() function of NumPy)
my_seven_array = np.full(tup_dim, 7, dtype=np.int16)
my_seven_array

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int16)

In [8]:
#Creating Identity matrix or array
my_identity_array = np.identity(4, dtype=np.float64)
my_identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Numpy - Arrays - Special Types of Arrays - Array with Random Values
1. NumPy array with all its elements values as random values (using random.rand() function of NumPy)
2. NumPy array with all its elements values as uninitialized values (initialized with some random values which you are not aware of - using empty() function of NumPy)

In [9]:
#Creating a random array using np.random.rand()
my_rand_array = np.random.rand(3,4)
print(my_rand_array)

[[0.73779856 0.73518215 0.68424951 0.95890389]
 [0.44599243 0.52769485 0.22464031 0.33336757]
 [0.05236978 0.85007567 0.48453663 0.26251505]]


In [10]:
#Creating an array with uninitialized values using empty()
tup_dim = (3,4)
my_uninitialized_array = np.empty(tup_dim)
print(my_uninitialized_array)

[[0.73779856 0.73518215 0.68424951 0.95890389]
 [0.44599243 0.52769485 0.22464031 0.33336757]
 [0.05236978 0.85007567 0.48453663 0.26251505]]


#Numpy - Arrays - Special Types of Arrays - Array with values within a particular range
1. By passing a range of values (using arange() function of NumPy)
2. By passing an equally spaced range of values (using linspace() function of NumPy)

In [11]:
#To create an array using arange()
#Suppose you want to create a NumPy array whose values should lie between 10 and 30 and the values should have a gap of the value of 5

my_range_array = np.arange(10, 30, 5)
print(my_range_array)

#The above NumPy array my_range_array will be filled with values between 10 and 30 (excluding 30) having a gap of the value of 5 between the consecutive values.

[10 15 20 25]


In [12]:
#Creating a NumPy array by passing an equally spaced range of values (using linspace() function of NumPy)
#Suppose you want to create a NumPy array whose values should lie between 0 and 5/3 
#and the consecutive values should have an equal amount of gap between them (equally spaced values).

my_spaced_array = np.linspace(0, 5/3, 6)
print(my_spaced_array)

#The above NumPy array my_spaced_array will have total of 6 values with values ranging between 0 and 5/3 (including 5/3) 
#and having an equal amount of gap between the consecutive values.

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]


#NumPy - Arrays - Attributes of a NumPy Array

In [13]:
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ])

In [14]:
# ndarray.ndim
#ndim represents the number of dimensions (axes) of the ndarray.
#e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], value of ndim will be 2. 
#This ndarray has two dimensions (axes) 

In [15]:
#ndarray.shape
#shape is a tuple of integers representing the size of the ndarray in each dimension.
#e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], value of shape will be (2,3) 
#because this ndarray has two dimensions - rows and columns - and the number of rows is 2 and the number of columns is 3

In [16]:
#ndarray.size
#size is the total number of elements in the ndarray. It is equal to the product of elements of the shape. 
#e.g. for this 2-dimensional array [ [3,4,6], [0,8,1]], shape is (2,3), 
#size will be product (multiplication) of 2 and 3 i.e. (2*3) = 6. Hence, the size is 6.

In [17]:
#ndarray.dtype
#dtype tells the data type of the elements of a NumPy array. 
#In NumPy array, all the elements have the same data type.
#e.g. for this NumPy array [ [3,4,6], [0,8,1]], dtype will be int64

In [18]:
#ndarray.itemsize
#itemsize returns the size (in bytes) of each element of a NumPy array.
#e.g. for this NumPy array [ [3,4,6], [0,8,1]], itemsize will be 8, 
#because this array consists of integers and size of integer (in bytes) is 8 bytes.

In [19]:
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.dtype)
print(my_array.itemsize)

2
(3, 4)
12
int64
8


#NumPy - Arrays - Resizing an Array : Resize()
* resize() function is used to create a new array of different sizes and dimensions.

* resize() can create an array of larger size than the original array.

1. To convert the original array into a bigger array, resize() will add more elements (than available in the original array) by copying the existing elements (repeated as many times as required) to fill the desired larger size.

In [20]:
my_arr = np.array([ [0,1], [2,3] ])
print(my_arr)
my_arr.resize( (2, 3) )  # need two rows and one column
print(my_arr)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 0]]


#NumPy - Arrays - Reshaping an Array : reshape()
* reshape() function is used to create a new array of the same size (as the original array) but of different desired dimensions.
* reshape() function will create an array with the same number of elements as the original array, i.e. of the same size as that of the original array. If you want to convert the original array to a bigger array, reshape() can’t add more elements(than available in the original array) to give you a bigger array.

In [21]:
#Case : 1 We already know the desired number dimensions (say rows and columns) of the reshaped array.
my_arr = np.arange(6)
print(my_arr)
my_new_arr = my_arr.reshape(2,3)
print(my_new_arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [22]:
#We know the desired number of columns, but don't know the desired number of rows of the reshaped array.
print(my_arr)
my_new_arr = my_arr.reshape(-1,3)
print(my_new_arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [23]:
#When you can't use reshape() function?
#You can't use reshape() function, when the size of the original array is different from your desired reshaped array. 
#If you try to reshape(), it will throw an error.


#Difference between resize() and reshape() :

In [24]:
#reshape() will create an array with the same number of elements as the original array, i.e. of the same ‘size’ as that of the original array. 
#If you want to convert the original array to a bigger array, 
#reshape() can’t add more elements(than available in the original array) to give you a bigger array. 
#Hence, reshape() is used to create a new array of the same size (as the original array) but of different desired dimensions.

#resize() can create an array of larger size than the original array. 
#To convert the original array into a bigger array, 
#resize() will add more elements (than available in the original array) 
#by copying the existing elements (repeated as many times as required) to fill the desired larger size. resize() 
#is used to create a new array of different sizes and dimensions.

#Numpy - Arrays - Example - Reshaping a complex array

In [25]:
china = load_sample_image("china.jpg")
print(china.shape)#to check the shape
image = china[150:220, 130:250]
print(image.shape)#to check the shape of image
height, width, channels = image.shape
print("height, width, channels : " + str(height), str(width), str(channels))


(427, 640, 3)
(70, 120, 3)
height, width, channels : 70 120 3


#converting  Colored into Grayscale image 
1. axis=0 represents the first dimension of an array, i.e. it represents the row
2. axis=1 represents the second dimension of an array, i.e. it represents the column
3. axis=2 represents the third dimension of an array, in this case, the third dimension is channels. 

In [26]:
#channels (axis=2) has 3 values (e.g. [68, 39, 44] ), and, mean of these 3 values is 50.33 
#Hence, value [68, 39, 44] will be replaced with value 50.33 after the step - image.mean(axis=2)
image_grayscale = image.mean(axis=2).astype(np.float32)
print(image_grayscale.shape)#to check the shape of gray scale image
images = image_grayscale.reshape(1, height, width, 1)
print(images.shape)#to check the dimensions of final output

(70, 120)
(1, 70, 120, 1)


#Numpy - Arrays - Indexing and Array Slicing

In [27]:
arr = np.array([1, 10, 31, 2, 18, 9, 22])

In [28]:
#If you want to extract a portion (a few elements) of this NumPy array, then you can use below syntax
part_arr = arr[2 : 5]
part_arr

array([31,  2, 18])

In [29]:
#If you want to extract a portion of the array, but by a gap of say 2 elements, then you can do so by using the below syntax
skip_arr = arr[1: :2]
skip_arr

array([10,  2,  9])

In [30]:
#Reversing of an array elements
my_orig_arr = np.array([1, 15, 3, 9, 26, 7, 89, 12])
my_rev_arr = my_orig_arr[ : : -1]
my_rev_arr

array([12, 89,  7, 26,  9,  3, 15,  1])

In [31]:
#Replacing selected elements of a NumPy array by a specific value
my_orig_arr2 = np.array([2, 9, 17, 13, 1, 4, 20, 57])
#Say, you want to replace a few elements (say from index 2 to 5) of the above NumPy array my_orig_arr2 by a value -6, you can do so by following the below steps:
my_orig_arr2[2 : 5] = -6
my_orig_arr2
#Please remember that this is only possible in a NumPy array, if you try to do this with a normal Python array, you will get an error.

array([ 2,  9, -6, -6, -6,  4, 20, 57])

In [32]:
#Extracting a slice(portion) of a NumPy array
apple = np.array([1,8,23,3,18,91,7,15])
apple_slice = apple[1:4]
print(apple_slice)
print(apple)
#If you change (replace) value in this slice (apple_slice array), the corresponding value will also get modified in its parent array apple.
apple_slice[1] = 99999
print(apple_slice)
print(apple)
#Original (parent) array from which the slice was extracted also gets modified if the slice value is modified.

[ 8 23  3]
[ 1  8 23  3 18 91  7 15]
[    8 99999     3]
[    1     8 99999     3    18    91     7    15]


In [33]:
#If you don't want original (parent) array values to get modified when its slice values are changing, 
#you can create the slice by using a copy() function in the slicing code syntax
apple_slice_new = apple[2:5].copy()
apple_slice_new[1] = 222222
print(apple_slice_new)
print(apple)

[ 99999 222222     18]
[    1     8 99999     3    18    91     7    15]


#Numpy - Arrays - Example - Extracting a portion of an image using array slicing

In [34]:
china = load_sample_image("china.jpg")
portion = china[120:250, 110:230]
print(portion.shape)

(130, 120, 3)


#Numpy - Arrays - Multi-Dimensional Arrays
1. multi_arr[1, 2]      -  to access value at row 1 and column 2
2. multi_arr[1, :]      -  to access value at row 1 and all columns
3. multi_arr[:, 1]      -  to access value at all rows and column 1
4. multi_arr[3:7, 2:10] - to access values at row numbers from 3 to 7 (row index 3 to 6) and at column numbers from 2 to 10 (column index 2 to 9)
* array[ row_start_index : row_end_index, column_start_index : column_end_index]


In [35]:
my_multi_arr = np.arange(20).reshape(4,5)
my_multi_arr_portion = my_multi_arr[2:4, 2:5]
print(my_multi_arr_portion)

[[12 13 14]
 [17 18 19]]


#Numpy - Arrays - Boolean Indexing

In [36]:
multi_arr = np.arange(12).reshape(3,4)
rows_wanted = np.array( [True, False, True] )
multi_arr_portion = multi_arr[rows_wanted, : ]
print(multi_arr)
print(rows_wanted)
print(multi_arr_portion)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ True False  True]
[[ 0  1  2  3]
 [ 8  9 10 11]]


#Numpy - Flattening a NumPy Array (converting to 1-D array) using ravel() function

In [37]:
my_2d_arr = np.arange(20).reshape(4,5)
my_1d_arr = my_2d_arr.ravel()
print(my_1d_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#Numpy - Mathematical Operations on NumPy Arrays

In [38]:
a_arr = np.array([60,70,80,90])
b_arr = np.arange(4)
c_arr = a_arr + b_arr #Addition element-wise
print(c_arr)

d_arr = np.array([60,70,80,90])
e_arr = np.arange(4)
f_arr = d_arr - e_arr #Subtraction element-wise
print(f_arr)

A_arr = np.array([ [ 5,9], [4, 7] ])
B_arr = np.array( [ [2, 8], [1, 6] ] )
M_arr = A_arr * B_arr #Multiplication element wise
print(M_arr)

C_arr = np.array([ [ 5,9], [4, 7] ])
D_arr = np.array( [ [2, 8], [1, 6] ] )
P_arr = np.dot(C_arr, D_arr)#Dot Product
print(P_arr)

#Division
R_div = np.array([ [25,65], [40,14] ])
S_div = np.array([ [2,10], [4,5] ])
T_div = R_div / S_div
print(T_div)


#Integer division
R_int_div = np.array([ [ 25,65], [40, 70] ])
S_int_div = np.array([ [2, 10], [8, 3] ] )
T_int_div = R_int_div // S_int_div
print(T_int_div)


#Modulus
R_mod = np.array([ [ 20,65], [40, 70] ])
S_mod = np.array([ [2, 10], [8, 3] ] )
T_mod = R_mod % S_mod
print(T_mod)


#Exponents
R_exp = np.array([ [4,2], [3,4] ])
S_exp = np.array([ [2,10], [4,5] ])
T_exp = R_exp ** S_exp
print(T_exp)


#Conditional Operators
U = np.array([ [22,45], [90,4]])
print(U[U<45])

[60 71 82 93]
[60 69 78 87]
[[10 72]
 [ 4 42]]
[[19 94]
 [15 74]]
[[12.5  6.5]
 [10.   2.8]]
[[12  6]
 [ 5 23]]
[[0 5]
 [0 1]]
[[  16 1024]
 [  81 1024]]
[22  4]


#Numpy - Mathematical and Statistical functions on NumPy Arrays

In [39]:
X = np.array( [ [-2.5, 3.1, 7],
                [10, 11, 12] ] )
#mean
print("mean = ", X.mean())

#Variance
print("Variance = ", X.var())

#standard deviation
print("Standard Deviation = ", X.std())

#minimum
print("min = ", X.min())

#maximum
print("max = ", X.max())

#sum
print("sum = ", X.sum())

#product
print("product = ", X.prod())

mean =  6.766666666666667
Variance =  25.855555555555554
Standard Deviation =  5.084835843520964
min =  -2.5
max =  12.0
sum =  40.6
product =  -71610.0


#Numpy - Mathematical and Statistical functions on NumPy Arrays - Sum(across axes)

In [40]:
Y = np.arange(24).reshape(2,3,4)
print(Y)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [41]:
# sum of these two matrices (element-wise)
print(Y.sum(axis=0))


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [42]:
# the sum of the (along the) rows of the two matrices (element-wise)
print(Y.sum(axis=1))


[[12 15 18 21]
 [48 51 54 57]]


In [43]:
#means the sum of the (along with the) columns of the two matrices (element-wise)
print(Y.sum(axis=2))

[[ 6 22 38]
 [54 70 86]]


#Numpy - Mathematical and Statistical functions on NumPy Arrays - Transpose

In [44]:
M = np.arange(6).reshape(2, 3)
print(M)
print("Transpose = ", M.T)

[[0 1 2]
 [3 4 5]]
Transpose =  [[0 3]
 [1 4]
 [2 5]]


#Numpy - Broadcasting in NumPy Arrays

In [45]:
#In any NumPy mathematical operation, if the shape of any of the participating arrays is not sufficient, broadcasting rules come into play.
#Broadcasting, generally, tries to adjust the shape of one or both of the arrays to bring them to required matching shape, 
#by copying the existing elements required number of times, so that the mathematical operation could be performed between the two NumPy arrays. 
#There are two broadcasting rules:

In [46]:
#First Rule: If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.
Q = np.array( [ [ [1, 3 ] ] ] )
P = np.array( [ 5 ] )

S = Q + P

print(Q)
print(P)
print(S)

[[[1 3]]]
[5]
[[[6 8]]]


In [47]:
#Second Rule: Arrays with a 1 along with a particular dimension act as if they had the size of the array with the largest shape along that dimension. 
#The value of the array element is repeated along that dimension.
X_broad = np.ones((3,3), dtype=float)
print(X_broad)
Y_broad = np.arange(3)
print(Y_broad)
Z_broad = X_broad + Y_broad
print(Z_broad)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [48]:
X_broad = np.arange(3).reshape((3,1))
print(X_broad)
Y_broad = np.arange(3)
print(Y_broad)
Z_broad = X_broad + Y_broad
print(Z_broad)

[[0]
 [1]
 [2]]
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
